
### Post Request
POST http://localhost:8080/store
Content-Type: application/json

{
    "key": "abc",
    "value": "123"
}

### Get Request
GET http://localhost:8081/store
Accept: application/json

### Get Request
GET http://localhost:8082/store
Accept: application/json
